package Controller;

public enum Message {

    LANCERPARTIE,
    DEUXJOUEURS,
    TROISJOUEURS,
    QUATREJOUEURS,
    ASSECHER,
    VALIDERASSECHEMENT,
    DEPLACER,
    VALIDERDEPLACEMENT,
    FINTOUR,
    AUTREACTION,
    ANNULER, 
    RECUPTRE, 
    UTILISECARTE, 
    ECHANGECARTE, 
    DEPLACEROBLIG,
    DEFAUSSE,
    DEFAUSSEOBLIG, 
    LANCERINSCRIPTION;
   
}
