package Controller;

public enum Message {

    LANCERPARTIE,
    DEUXJOUEURS,
    TROISJOUEURS,
    QUATREJOUEURS,
    ASSECHER,
    VALIDERASSECHEMENT,
    DEPLACER,
    VALIDERDEPLACEMENT,
    FINTOUR,
    AUTREACTION,
    ANNULER,
    UTILISATION_CAPACITE,
    DEFFAUSSER,
    INVOQUER,
    DONNER,
    UTILISER_CARTE,
    DEPLACEROBLIG,
    RECUPTRE, 
    UTILISECARTE, 
    ECHANGECARTE,
}
